# -*- coding: utf-8 -*-
"""迁移清单：ppci/ppci 旧路径 → src/qcc 新路径。

需求.md 要求：按模块迁移（而非整个 ppci 目录），保留 C 前端 +
arm/risc-v/x86_64 后端 + ELF 支持所需的完整依赖闭包，
剔除其他语言前端、CLI、build 系统、调试器等无关模块。
"""

# 目录前缀映射（模块级别，用于 import 重写的最长前缀匹配）
PREFIX_MAP = {
    "ppci.api": "qcc.api",
    "ppci.common": "qcc.common",
    "ppci.ir": "qcc.midend.ir",
    "ppci.irutils": "qcc.midend.irutils",
    "ppci.opt": "qcc.midend.opt",
    "ppci.graph": "qcc.midend.graph",
    "ppci.lang.common": "qcc.frontend.common",
    "ppci.lang.generic": "qcc.frontend.generic",
    "ppci.lang.tools": "qcc.frontend.tools",
    "ppci.lang.c": "qcc.frontend.c",
    "ppci.codegen": "qcc.backend.codegen",
    "ppci.arch": "qcc.backend.arch",
    "ppci.binutils": "qcc.backend.binutils",
    "ppci.format": "qcc.backend.format",
    "ppci.utils": "qcc.utils",
    "ppci": "qcc",
}

# 文件级清单：old_rel → new_rel（相对各自包根）
FILE_MAP = {
    # ---- 根：总入口与公共设施 ----
    "api.py": "api.py",
    "common.py": "common.py",
    # ---- ① frontend：C 语言前端 ----
    "lang/common.py": "frontend/common.py",
    "lang/generic/__init__.py": "frontend/generic/__init__.py",
    "lang/generic/nodes.py": "frontend/generic/nodes.py",
    # 词法/语法工具基础（yacc 供 codegen/burg 生成器使用）
    "lang/tools/__init__.py": "frontend/tools/__init__.py",
    "lang/tools/baselex.py": "frontend/tools/baselex.py",
    "lang/tools/common.py": "frontend/tools/common.py",
    "lang/tools/earley.py": "frontend/tools/earley.py",
    "lang/tools/grammar.py": "frontend/tools/grammar.py",
    "lang/tools/handlexer.py": "frontend/tools/handlexer.py",
    "lang/tools/lr.py": "frontend/tools/lr.py",
    "lang/tools/recursivedescent.py": "frontend/tools/recursivedescent.py",
    "lang/tools/yacc.py": "frontend/tools/yacc.py",
    # C 前端全部模块
    "lang/c/__init__.py": "frontend/c/__init__.py",
    "lang/c/api.py": "frontend/c/api.py",
    "lang/c/builder.py": "frontend/c/builder.py",
    "lang/c/castxml.py": "frontend/c/castxml.py",
    "lang/c/codegenerator.py": "frontend/c/codegenerator.py",
    "lang/c/context.py": "frontend/c/context.py",
    "lang/c/eval.py": "frontend/c/eval.py",
    "lang/c/init.py": "frontend/c/init.py",
    "lang/c/lexer.py": "frontend/c/lexer.py",
    "lang/c/macro.py": "frontend/c/macro.py",
    "lang/c/nodes/__init__.py": "frontend/c/nodes/__init__.py",
    "lang/c/nodes/declarations.py": "frontend/c/nodes/declarations.py",
    "lang/c/nodes/expressions.py": "frontend/c/nodes/expressions.py",
    "lang/c/nodes/nodes.py": "frontend/c/nodes/nodes.py",
    "lang/c/nodes/statements.py": "frontend/c/nodes/statements.py",
    "lang/c/nodes/types.py": "frontend/c/nodes/types.py",
    "lang/c/nodes/visitor.py": "frontend/c/nodes/visitor.py",
    "lang/c/options.py": "frontend/c/options.py",
    "lang/c/parser.py": "frontend/c/parser.py",
    "lang/c/preprocessor.py": "frontend/c/preprocessor.py",
    "lang/c/printer.py": "frontend/c/printer.py",
    "lang/c/scope.py": "frontend/c/scope.py",
    "lang/c/semantics.py": "frontend/c/semantics.py",
    "lang/c/synthesize.py": "frontend/c/synthesize.py",
    "lang/c/token.py": "frontend/c/token.py",
    "lang/c/utils.py": "frontend/c/utils.py",
    # ---- ② midend：IR 与优化 ----
    "ir.py": "midend/ir.py",
    "irutils/__init__.py": "midend/irutils/__init__.py",
    "irutils/builder.py": "midend/irutils/builder.py",
    "irutils/instrument.py": "midend/irutils/instrument.py",
    "irutils/io.py": "midend/irutils/io.py",
    "irutils/link.py": "midend/irutils/link.py",
    "irutils/reader.py": "midend/irutils/reader.py",
    "irutils/verify.py": "midend/irutils/verify.py",
    "irutils/writer.py": "midend/irutils/writer.py",
    "opt/__init__.py": "midend/opt/__init__.py",
    "opt/cjmp.py": "midend/opt/cjmp.py",
    "opt/clean.py": "midend/opt/clean.py",
    "opt/constantfolding.py": "midend/opt/constantfolding.py",
    "opt/cse.py": "midend/opt/cse.py",
    "opt/load_after_store.py": "midend/opt/load_after_store.py",
    "opt/mem2reg.py": "midend/opt/mem2reg.py",
    "opt/tailcall.py": "midend/opt/tailcall.py",
    "opt/transform.py": "midend/opt/transform.py",
    "graph/__init__.py": "midend/graph/__init__.py",
    "graph/cfg.py": "midend/graph/cfg.py",
    "graph/digraph.py": "midend/graph/digraph.py",
    "graph/domtree.py": "midend/graph/domtree.py",
    "graph/graph.py": "midend/graph/graph.py",
    "graph/lt.py": "midend/graph/lt.py",
    "graph/maskable_graph.py": "midend/graph/maskable_graph.py",
    "graph/relooper.py": "midend/graph/relooper.py",
    "graph/algorithm/__init__.py": "midend/graph/algorithm/__init__.py",
    "graph/algorithm/fixed_point_dominator.py": (
        "midend/graph/algorithm/fixed_point_dominator.py"
    ),
    # ---- ③ backend：代码生成 → 机器码 ----
    "codegen/__init__.py": "backend/codegen/__init__.py",
    "codegen/burg.py": "backend/codegen/burg.py",
    "codegen/burg.grammar": "backend/codegen/burg.grammar",  # 数据文件！
    "codegen/codegen.py": "backend/codegen/codegen.py",
    "codegen/dagsplit.py": "backend/codegen/dagsplit.py",
    "codegen/flowgraph.py": "backend/codegen/flowgraph.py",
    "codegen/instructionscheduler.py": "backend/codegen/instructionscheduler.py",
    "codegen/instructionselector.py": "backend/codegen/instructionselector.py",
    "codegen/interferencegraph.py": "backend/codegen/interferencegraph.py",
    "codegen/irdag.py": "backend/codegen/irdag.py",
    "codegen/peephole.py": "backend/codegen/peephole.py",
    "codegen/registerallocator.py": "backend/codegen/registerallocator.py",
    "codegen/selectiongraph.py": "backend/codegen/selectiongraph.py",
    "codegen/treematcher.py": "backend/codegen/treematcher.py",
    # arch 共享设施 + example（测试用教学架构）
    "arch/__init__.py": "backend/arch/__init__.py",
    "arch/arch.py": "backend/arch/arch.py",
    "arch/arch_info.py": "backend/arch/arch_info.py",
    "arch/asm_printer.py": "backend/arch/asm_printer.py",
    "arch/cc.py": "backend/arch/cc.py",
    "arch/data_instructions.py": "backend/arch/data_instructions.py",
    "arch/effects.py": "backend/arch/effects.py",
    "arch/encoding.py": "backend/arch/encoding.py",
    "arch/example.py": "backend/arch/example.py",
    "arch/generic_instructions.py": "backend/arch/generic_instructions.py",
    "arch/isa.py": "backend/arch/isa.py",
    "arch/registers.py": "backend/arch/registers.py",
    "arch/stack.py": "backend/arch/stack.py",
    "arch/target_list.py": "backend/arch/target_list.py",
    "arch/token.py": "backend/arch/token.py",
    # ARM 后端
    "arch/arm/__init__.py": "backend/arch/arm/__init__.py",
    "arch/arm/arch.py": "backend/arch/arm/arch.py",
    "arch/arm/arm_instructions.py": "backend/arch/arm/arm_instructions.py",
    "arch/arm/arm_relocations.py": "backend/arch/arm/arm_relocations.py",
    "arch/arm/isa.py": "backend/arch/arm/isa.py",
    "arch/arm/registers.py": "backend/arch/arm/registers.py",
    "arch/arm/thumb_instructions.py": "backend/arch/arm/thumb_instructions.py",
    "arch/arm/thumb_relocations.py": "backend/arch/arm/thumb_relocations.py",
    # RISC-V 后端
    "arch/riscv/__init__.py": "backend/arch/riscv/__init__.py",
    "arch/riscv/arch.py": "backend/arch/riscv/arch.py",
    "arch/riscv/asm_printer.py": "backend/arch/riscv/asm_printer.py",
    "arch/riscv/instructions.py": "backend/arch/riscv/instructions.py",
    "arch/riscv/registers.py": "backend/arch/riscv/registers.py",
    "arch/riscv/relocations.py": "backend/arch/riscv/relocations.py",
    "arch/riscv/rvc_instructions.py": "backend/arch/riscv/rvc_instructions.py",
    "arch/riscv/rvc_relocations.py": "backend/arch/riscv/rvc_relocations.py",
    "arch/riscv/rvf_instructions.py": "backend/arch/riscv/rvf_instructions.py",
    "arch/riscv/rvfx_instructions.py": "backend/arch/riscv/rvfx_instructions.py",
    "arch/riscv/tokens.py": "backend/arch/riscv/tokens.py",
    # x86_64 后端
    "arch/x86_64/__init__.py": "backend/arch/x86_64/__init__.py",
    "arch/x86_64/arch.py": "backend/arch/x86_64/arch.py",
    "arch/x86_64/elf.py": "backend/arch/x86_64/elf.py",
    "arch/x86_64/instructions.py": "backend/arch/x86_64/instructions.py",
    "arch/x86_64/registers.py": "backend/arch/x86_64/registers.py",
    "arch/x86_64/sse2_instructions.py": (
        "backend/arch/x86_64/sse2_instructions.py"
    ),
    "arch/x86_64/x87_instructions.py": (
        "backend/arch/x86_64/x87_instructions.py"
    ),
    # 二进制工具：目标文件、汇编器、链接器
    "binutils/__init__.py": "backend/binutils/__init__.py",
    "binutils/archive.py": "backend/binutils/archive.py",
    "binutils/assembler.py": "backend/binutils/assembler.py",
    "binutils/debuginfo.py": "backend/binutils/debuginfo.py",
    "binutils/disasm.py": "backend/binutils/disasm.py",
    "binutils/layout.py": "backend/binutils/layout.py",
    "binutils/linker.py": "backend/binutils/linker.py",
    "binutils/objectfile.py": "backend/binutils/objectfile.py",
    "binutils/outstream.py": "backend/binutils/outstream.py",
    # 输出格式：ELF（需求要求）+ hex
    "format/__init__.py": "backend/format/__init__.py",
    "format/header.py": "backend/format/header.py",
    "format/hexfile.py": "backend/format/hexfile.py",
    "format/elf/__init__.py": "backend/format/elf/__init__.py",
    "format/elf/file.py": "backend/format/elf/file.py",
    "format/elf/headers.py": "backend/format/elf/headers.py",
    "format/elf/reader.py": "backend/format/elf/reader.py",
    "format/elf/string.py": "backend/format/elf/string.py",
    "format/elf/writer.py": "backend/format/elf/writer.py",
    # ---- 公共工具 ----
    "utils/__init__.py": "utils/__init__.py",
    "utils/binary_txt.py": "utils/binary_txt.py",
    "utils/bitfun.py": "utils/bitfun.py",
    "utils/chunk.py": "utils/chunk.py",
    "utils/collections.py": "utils/collections.py",
    "utils/graph2svg.py": "utils/graph2svg.py",
    "utils/hexdump.py": "utils/hexdump.py",
    "utils/integer_set.py": "utils/integer_set.py",
    "utils/reporting.py": "utils/reporting.py",
    "utils/tree.py": "utils/tree.py",
}
